export default{
    // 登录
    login: '/login',
    // 注销
    logout: '/logout',
    // 上传
    upload: '/upload',
    // 注册
    register: '/register',
    // 获取动画区
    getVideoList: '/get-video-list',
    // 获取直播区
    getLiveList: '/get-live-list',
    // 获取视频信息
    getVideo: '/get-video',
    // 发送弹幕接口
    sentBarrage: '/sent-barrage',
    deleteBarrage: '/delete-barrage'
}
